### ISSUE TITLE
Missing config.json

### ISSUE THREAD

**Issue by dbfy** [RuMont/DiscordSheet#1]
> Requires a config.json file to include the bot's client token and prefix. It is recommended to include the spreadsheet inside this file.

Can you post an example json?? thanks.

**Comment by RuMont** [comment]
Sure, just create a .json file named config.json with the following structure and should it be:
```
{
    "client_token": "Your token goes here",
    "prefix": "Whatever prefix you like, could be ! or %"
}
```

**Comment by dbfy** [comment]
thankies
